exclude: archive

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-case-conflict
      - id: check-toml
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: mixed-line-ending
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: pretty-format-json
        args:
          - --autofix
      - id: requirements-txt-fixer

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.1
    hooks:
      - id: isort
        name: Run isort to sort imports
        files: \.py$
        exclude: ^build/.*$|^.tox/.*$|^venv/.*$
        args:
          - --lines-after-imports=2
          - --multi-line=3
          - --trailing-comma
          - --force-grid-wrap=0
          - --use-parentheses
          - --ensure-newline-before-comments
          - --line-length=88

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
        - id: flake8
          args:
            - --per-file-ignores=test_*:E501
            - --max-line-length=88
            - --ignore=E203,W503

  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
        - id: black
          args:
            - --safe
