version: '3'

services:

  webserver:
    image: ghcr.io/wordpress/openverse-catalog:${DOCKER_IMAGE_TAG:-latest}
    env_file: .env
    restart: always
    ports:
      - "${AIRFLOW_PORT}:8080"
    volumes:
      - airflow:/var/workflow_output
      - ./openverse_catalog/dags:/usr/local/airflow/openverse_catalog/dags

volumes:
  airflow:
