version: '3'

services:

  webserver:
    build:
      context: .
      args:
        - OUTPUT_DIR=${OUTPUT_DIR}
        - REQUIREMENTS_FILE=requirements_prod.txt
    env_file: .env
    restart: always
    ports:
      - "${AIRFLOW_PORT}:8080"
    volumes:
      - airflow-volume:/tmp/workflow_output

volumes:
  airflow-volume:
