version: '3'

services:
  postgres:
    build: ./local_postgres
    environment:
      - POSTGRES_USER=deploy
      - POSTGRES_PASSWORD=deploy
      - POSTGRES_DB=openledger
    env_file: .env
    ports:
      - "5434:5432"
    volumes:
      - /tmp/docker_postgres_data:/var/lib/postgresql/data

  s3:
    build:
      context: ./local_s3
    ports:
      - "5000:5000"

  webserver:
    build:
      context: .
      args:
        - OUTPUT_DIR=${OUTPUT_DIR}
        - REQUIREMENTS_FILE=requirements_prod.txt
    env_file: .env
    restart: always
    depends_on:
      - postgres
      - s3
    ports:
      - "${AIRFLOW_PORT}:8080"
    volumes:
      - airflow-volume:/tmp/workflow_output

volumes:
  airflow-volume:
