version: '3'

services:
  # Services only needed for local development
  postgres:
    build: ./local_postgres
    environment:
      - POSTGRES_USER=deploy
      - POSTGRES_PASSWORD=deploy
      - POSTGRES_DB=openledger
    env_file: .env
    ports:
      - "5434:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  s3:
    build:
      context: ./local_s3
    ports:
      - "5000:5000"

  # Dev changes for the webserver container
  webserver:
    depends_on:
      - postgres
      - s3
    volumes:
      - ./dags:/usr/local/airflow/dags
    build:
      args:
        - REQUIREMENTS_FILE=requirements_dev.txt

volumes:
  postgres-volume:
