name: CI + CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Cache pre-commit envs
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit to lint files
        run: |
          pip install pre-commit
          just lint

  build-images:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          file: docker/airflow/Dockerfile
          push: false
          tags: openverse-catalog
          cache-from: type=gha,scope=catalog
          cache-to: type=gha,scope=catalog
          outputs: type=docker,dest=/tmp/catalog.tar

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: catalog
          path: /tmp/catalog.tar

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs:
      - lint
      - build-images
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1

      - name: Change permissions for Docker steps
        run: chmod -R 777 openverse_catalog/ tests/

      - name: Test
        # Randomize test order to suss out any unseen dependencies
        run: |
          just build
          just test --random-order

  push:
    name: Publish Docker images
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    needs:
      - test
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: catalog
          path: /tmp

      - name: Load and tag image
        run: |
          docker load --input /tmp/catalog.tar
          docker tag openverse-catalog \
            ghcr.io/wordpress/openverse-catalog:latest
          docker tag openverse-catalog \
            ghcr.io/wordpress/openverse-catalog:${{ github.sha }}
          docker tag openverse-catalog \
            ghcr.io/wordpress/openverse-catalog:${{ github.ref_name }}
          docker push --all-tags ghcr.io/wordpress/openverse-catalog
