name: CI + CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'release' && 'release' || github.ref }}
  # Don't continue building images for a PR if the PR is updated quickly
  # For other workflows, allow them to complete and just block on them. This
  # ensures deployments in particular to happen in series rather than parallel.
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: extractions/setup-just@v1

      - name: Get Python version
        id: python-version
        run: echo "::set-output name=value::$(just py-version)"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ steps.python-version.outputs.value }}"

      - name: Cache pre-commit envs
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit to lint files
        run: |
          pip install pre-commit
          just lint

  build-images:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: extractions/setup-just@v1

      - name: Get Python version
        id: python-version
        run: echo "::set-output name=value::$(just py-version)"

      - name: Get Airflow version
        id: airflow-version
        run: echo "::set-output name=value::$(just airflow-version)"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          file: docker/airflow/Dockerfile
          push: false
          tags: openverse-catalog
          cache-from: type=gha,scope=catalog
          cache-to: type=gha,scope=catalog
          outputs: type=docker,dest=/tmp/catalog.tar
          build-args: |
            PROJECT_PY_VERSION=${{ steps.python-version.outputs.value }}
            PROJECT_AIRFLOW_VERSION=${{ steps.airflow-version.outputs.value }}

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: catalog
          path: /tmp/catalog.tar

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs:
      - lint
      - build-images
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1

      - name: Change permissions for Docker steps
        run: chmod -R 777 openverse_catalog/ tests/

      - name: Build dev container
        # The containers must be rebuilt here because we need the dev dependencies
        # rather than the production ones
        run: just build

      - name: Check DAG documentation
        run: just generate-dag-docs true

      - name: Test
        run: just test --extended

  push:
    name: Publish Docker images
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    needs:
      - test
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download image
        uses: actions/download-artifact@v3
        with:
          name: catalog
          path: /tmp

      - name: Load and tag image
        run: |
          docker load --input /tmp/catalog.tar
          docker tag openverse-catalog \
            ghcr.io/wordpress/openverse-catalog:latest
          docker tag openverse-catalog \
            ghcr.io/wordpress/openverse-catalog:${{ github.sha }}
          docker tag openverse-catalog \
            ghcr.io/wordpress/openverse-catalog:${{ github.ref_name }}
          docker push --all-tags ghcr.io/wordpress/openverse-catalog
