name: Automated testing workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - name: Change permissions for Docker steps
        run: chmod -R 777 openverse_catalog/ tests/
      - name: Test
        run: |
          just up
          sleep 5  # TODO: Find a more thorough way of addressing this
          just test
