name: Automated testing workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - name: Change permissions for Docker steps
        run: chmod -R 777 openverse_catalog/ tests/
      - name: Test
        # Randomize test order to suss out any unseen dependencies
        run: just test --random-order
