name: Release Drafter

on:
  push:
    branches:
      - develop

jobs:
  update_release_draft:
    name: Update draft release
    runs-on: ubuntu-latest
    steps:
      - name: Update draft release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
